import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ConvexClientProvider } from "./ConvexClientProvider"
import MarketingLayout from '@/components/marketing-layout'
import DashboardLayout from '@/components/dashboard-layout'
import AuthSync from '@/components/AuthSync'
import { ThemeProvider } from "@/components/theme-provider"

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Quimica',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <ConvexClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <body>
              <AuthSync/>

              <SignedOut>
                <MarketingLayout>
                  {children}
                </MarketingLayout>
              </SignedOut>

              <SignedIn>
                <DashboardLayout>
                  {children}
                </DashboardLayout>
              </SignedIn>
            </body>
          </ThemeProvider>
        </ConvexClientProvider>
      </html>
    </ClerkProvider>
  )
}